### ISSUE TITLE
Using getRandomBook causes books/articles with fewer highlights to be shown relatively more

### ISSUE THREAD

**Issue by TedisAgolli** [TedisAgolli/readwise-new-tab#2]
> I am seeing very few highlights from my books, and many highlights from my articles, as right now with the getRandomBook logic all books/articles are weighed the same, but there are many more articles than books and books have many highlights per-book. If instead you moved all highlights into a list and randomly selected from all highlights with equal probability, the resurfacing would work more like Readwise's and show more book highlights :)

**Comment by TristanH** [comment]
I'd recommend looking at how @jsonMartin does this in his Readwise Mirror obsidian plugin:

https://github.com/jsonMartin/readwise-mirror/blob/38fb9567e158d70dbf2d210b21d1019bd3fa1461/readwiseApi.ts#L82

Seems to fetch all readwise data quite efficiently!

**Comment by TedisAgolli** [comment]
That's very useful, thanks!

**Comment by TedisAgolli** [comment]
@TristanH 
Here's a hacky solution I used to not have to list all highlights.
1. Call ```/highlights``` once, save the ```count``` (total number of highlights in the account).
2. On every other refresh generate a random number from 0 to ```count```.
3. Call ```/highlights``` like this ```https://readwise.io/api/v2/highlights?page_size=1&page=${count}```
So rather than getting 1k or more quotes every refresh, or caching the quotes in localStorage which has caused a StorageQuota error before, use ```page_size=1``` and ```page=${random number}``` to get only the quote you need.
4. Refresh ```count``` from the API call in step 3

**Comment by TristanH** [comment]
Cool! I'm actually a littttle worried about this approach, as I think it might hit the rate-limit pretty rapidly. I've found the new tab thing pretty addicting, so I'll often refresh my new tab like 10 times in a row -- in cases like that I believe you'd hit the rate limit quiiite quickly. Also the API is not thaaat fast, so you would likely cause the user to have to wait in some cases if it's going to be called every time the user wants to see a quote? But maybe I'm misunderstanding.

re:localstorage, indeed that sucks, but if you use indexeddb you should have ~unlimited storage and be well off to just cache everything! the API is a little more annoying though, I like using [localForage](https://localforage.github.io/localForage/) for it. Just a suggestion!
