### ISSUE TITLE
Images need a max width/height

### ISSUE THREAD

**Issue by TristanH** [TedisAgolli/readwise-new-tab#4]
Occasionally we'll get very large images from eg podcasts :P

<img width="1792" alt="CleanShot 2021-06-07 at 10 11 00@2x" src="https://user-images.githubusercontent.com/1284332/121061482-e3be0a80-c791-11eb-8f47-b80300d81bca.png">

**Comment by TedisAgolli** [comment]
https://github.com/TedisAgolli/readwise-new-tab/commit/711de11a2e2dd36f42a62f6450832798e80cc838#diff-bb6d203bb58bb1f5ab57dc04ae202691ddee955164502d8e2e46dc874cd74300R16 
Should be solved by this.
