### ISSUE TITLE
Images don't seem to have src set in latest version from Chrome store

### ISSUE THREAD

**Issue by TristanH** [TedisAgolli/readwise-new-tab#5]
Maybe already fixed up stream, but just so you know:

<img width="813" alt="CleanShot 2021-06-09 at 09 46 39@2x" src="https://user-images.githubusercontent.com/1284332/121395864-d4b99280-c920-11eb-939b-0e64c1e7a87b.png">

**Comment by TedisAgolli** [comment]
I'm not seeing the issue on my side. If you still see it could you check whether the source is actually not set or if it's just not getting the image?

**Comment by TristanH** [comment]
<img width="1554" alt="CleanShot 2021-06-10 at 15 38 21@2x" src="https://user-images.githubusercontent.com/1284332/121605847-175f9580-ca1b-11eb-81b4-ab6b4a2ae297.png">

Yep, no image src. Refreshed about 20 times and the same every time!

**Comment by TristanH** [comment]
For some reason this call:

https://github.com/TedisAgolli/readwise-new-tab/blob/17078c2c2411e6cfebd4f0634812e0bd80a23caa/src/background.ts#L71

Always seems to return `{}`... maybe I have too many books or something and they're not all getting stored locally?

**Comment by TedisAgolli** [comment]
Good catch :/ I'll try to push a new update this weekend to use IndexedDB which seems like it should fix this.

**Comment by TristanH** [comment]
:D all good, excited for that~!

**Comment by TedisAgolli** [comment]
Any luck with the new update?

**Comment by TristanH** [comment]
Sorry for missing this -- YES, it works great :D 🔥

**Comment by TedisAgolli** [comment]
That's great to hear!
