### ISSUE TITLE
Possible to follow settings of daily review?

### ISSUE THREAD

**Issue by jamie9090** [TedisAgolli/readwise-new-tab#8]
Hi there,

Love this plugin!

Is it possible to have the plugin follow the "daily review" frequency settings?

Thank you,
Jamie

**Comment by TedisAgolli** [comment]
Thank you for the kind words!

Can you elaborate a bit more? Does that mean you want it to show some articles more often and some less often?

**Comment by jamie9090** [comment]
Sure - I have some  books set to "do not show highlights in daily reviews".

So I'm hoping we can follow the "daily review" settings which allows you to also then "hide" some books from showing up in highlights.

**Comment by TedisAgolli** [comment]
The extension is currently at least ignoring discarded highlights. 
If you're referring to things such as "Show more/less often", I am currently not able to get that information through the API. Even if I could, it would be beyond the scope of this simple extension to handle that. It would require storing information about how often every highlight has been shown already and coming up with an algorithm to decide when it's valuable to show it again. That's a good part of Readwises` secret sauce and would currently be too much work for me to go into. 
Hope I understood your concern!

**Comment by jamie9090** [comment]
Thank you for your response! No problem at all.
